version:  "3.8"

services:
  web:
    build:  "./web"
    ports:
      - "5000:5000"
    links:
      - my_db
    environment:
      - api_key_virus_total=${api_key_virus_total}
      - api_key_abuseIP=${api_key_abuseIP}
  my_db:
    build: "./database"
